package kz.ws.bee.court.sk.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2019-09-27T11:22:52.111+06:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebServiceClient(name = "SkCasesServiceService", 
                  wsdlLocation = "http://localhost:10406/ws/sk-cases?wsdl",
                  targetNamespace = "http://sk.court.bee.ws.kz/wsdl") 
public class SkCasesServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sk.court.bee.ws.kz/wsdl", "SkCasesServiceService");
    public final static QName SkCasesPort = new QName("http://sk.court.bee.ws.kz/wsdl", "skCasesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:10406/ws/sk-cases?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SkCasesServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:10406/ws/sk-cases?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SkCasesServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SkCasesServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SkCasesServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SkCasesServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SkCasesServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SkCasesServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SkCases
     */
    @WebEndpoint(name = "skCasesPort")
    public SkCases getSkCasesPort() {
        return super.getPort(SkCasesPort, SkCases.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SkCases
     */
    @WebEndpoint(name = "skCasesPort")
    public SkCases getSkCasesPort(WebServiceFeature... features) {
        return super.getPort(SkCasesPort, SkCases.class, features);
    }

}
